name: Codacy Analysis

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'  

      - name: Build, test, and generate JaCoCo report
        run: |
          ./gradlew clean test jacocoTestReport

      - name: Download Codacy Coverage Reporter
        run: |
          wget https://github.com/codacy/codacy-coverage-reporter/releases/download/12.1.4/codacy-coverage-reporter-linux 
          chmod +x codacy-coverage-reporter-linux

      - name: Upload coverage to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          # JaCoCo 리포트의 경로를 -r 옵션으로 지정 (Gradle에서 생성되는 XML 위치)
          ./codacy-coverage-reporter-linux \
            report \
            --language Java \
            --coverage-reporter jacoco \
            --report-path build/reports/jacoco/test/jacocoTestReport.xml
