name: Codacy Analysis

on:
  push:
    branches: [ "develop" ]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      # (1) 소스코드 체크아웃
      - name: Check out repository
        uses: actions/checkout@v3

      # (2) application.yml 생성
      - name: Create application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APP_YML }}" > src/main/resources/application.yml

      # (3) JDK 설정
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'  

      # (4) Gradle 빌드 (테스트 포함)
      - name: Build and Test (Gradle)
        run: |
          chmod +x ./gradlew
          ./gradlew clean test jacocoTestReport

      # (5) Codacy 코드 분석 실행
      - name: Run Codacy Analysis
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
            -t $CODACY_PROJECT_TOKEN \
            -r build/reports/jacoco/test/jacocoTestReport.xml